version: '3.8'

services:
  cashoutservices:
    image: ${DOCKER_REGISTRY-}cashoutservices
    build:
      context: .
      dockerfile: src\CashoutServices\Dockerfile
    networks:
      - app-network
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=192.168.1.100  # Change to your external MySQL IP/hostname
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=your_password
      - DB_NAME=cashoutdb

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    command: redis-server --requirepass your_strong_password  # Optional password protection

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge