version: '3.8'

services:
  cashoutservices:
    image: cashoutservices
    build:
      context: .
      dockerfile: src/CashoutServices/Dockerfile
    networks:
      - app-network
    depends_on:
      - redis
    ports:
      - "5000:5000"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    
volumes:
  redis_data:

networks:
  app-network:
    driver: bridge
